name: mkdocs-ci
on:
  push:
    branches:
      - main
      - documentation
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Pull LFS files
        run: git lfs pull
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.14.0"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdoxy mkdocs-awesome-nav
      - run: mkdocs gh-deploy --force -b documentation
